ALTER TABLE users ADD COLUMN IF NOT EXISTS is_tasker BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tasker_bio VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tasker_skills TEXT[];
