import com.google.firebase.appdistribution.gradle.firebaseAppDistribution
import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.google.services)
    alias(libs.plugins.firebase.appdistribution)
    alias(libs.plugins.app.versioning)
    id("org.jetbrains.kotlin.plugin.compose") version "2.0.21"
    id("jacoco")
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

// Load keystore properties if available
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(keystorePropertiesFile.inputStream())
}

// Load local.properties for per-developer overrides (e.g., API_BASE_URL)
val localPropertiesFile = rootProject.file("local.properties")
val localProperties = Properties()
if (localPropertiesFile.exists()) {
    localProperties.load(localPropertiesFile.inputStream())
}
val mapTilerApiKey = localProperties.getProperty("MAPTILER_API_KEY", "__MAPTILER_API_KEY__")

// CalVer versioning from Git tags (JetBrains-style: YYYY.R or YYYY.R.P)
// Tags like "2026.1", "2026.2.1" are parsed into versionCode and versionName.
// versionCode = YYYY * 10000 + R * 100 + P
appVersioning {
    gitRootDirectory.set(rootProject.file("../"))
    tagFilter.set("android/*")
    overrideVersionCode { gitTag, _, _ ->
        val version = gitTag.toString().removePrefix("android/")
        val parts = version.split(".")
        val year = parts[0].toInt()
        val release = parts.getOrElse(1) { "0" }.toInt()
        val patch = parts.getOrElse(2) { "0" }.toInt()
        year * 10000 + release * 100 + patch
    }
    overrideVersionName { gitTag, _, variantInfo ->
        val version = gitTag.toString().removePrefix("android/")
        val suffix = when {
            variantInfo.flavorName == "dev" -> "-dev"
            variantInfo.buildType == "release" -> "-rel"
            else -> ""
        }
        "$version$suffix"
    }
}

android {
    namespace = "com.viecz.vieczandroid"
    compileSdk = 36

    // Java and Kotlin must target the same JVM version
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    if (keystorePropertiesFile.exists()) {
        signingConfigs {
            create("release") {
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
            }
        }
    }

    defaultConfig {
        applicationId = "com.viecz.vieczandroid"
        minSdk = 30
        targetSdk = 36
        // versionCode and versionName are generated by app-versioning plugin from Git tags
        buildConfigField("String", "MAPTILER_API_KEY", "\"$mapTilerApiKey\"")

        testInstrumentationRunner = "com.viecz.vieczandroid.HiltTestRunner"
    }

    flavorDimensions += "environment"

    productFlavors {
        create("dev") {
            dimension = "environment"
            applicationIdSuffix = ".dev"
            val devUrl = localProperties.getProperty(
                "API_BASE_URL_DEV",
                "http://10.0.2.2:9999/api/v1/"
            )
            buildConfigField("String", "API_BASE_URL", "\"$devUrl\"")

            // Google OAuth Client ID (load from local.properties)
            val googleClientId = localProperties.getProperty("GOOGLE_CLIENT_ID", "")
            buildConfigField("String", "GOOGLE_CLIENT_ID", "\"$googleClientId\"")

            resValue("string", "app_name", "Viecz Dev")
        }
        create("prod") {
            dimension = "environment"
            val prodUrl = localProperties.getProperty(
                "API_BASE_URL_PROD",
                "https://viecz-api.fishcmus.io.vn/api/v1/"
            )
            buildConfigField("String", "API_BASE_URL", "\"$prodUrl\"")

            // Google OAuth Client ID (load from local.properties)
            val googleClientId = localProperties.getProperty("GOOGLE_CLIENT_ID", "")
            buildConfigField("String", "GOOGLE_CLIENT_ID", "\"$googleClientId\"")

            resValue("string", "app_name", "Viecz")
        }
    }

    buildTypes {
        debug {
            enableUnitTestCoverage = true
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            if (keystorePropertiesFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            firebaseAppDistribution {
                artifactType = "APK"
                groups = "internal-testers"
            }
        }
    }
    kotlinOptions {
        jvmTarget = "21"  // Kotlin 2.0.21 supports up to JVM target 21
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests {
            isReturnDefaultValues = true
            isIncludeAndroidResources = true
        }
    }

    // Test profile filtering via project properties:
    //   ./gradlew connectedDevDebugAndroidTest -PexcludeRealServer  (mock-only)
    //   ./gradlew connectedDevDebugAndroidTest -PonlyRealServer     (real-server only)
    if (project.hasProperty("excludeRealServer")) {
        defaultConfig.testInstrumentationRunnerArguments["notAnnotation"] =
            "com.viecz.vieczandroid.e2e.RealServerTest"
    }
    if (project.hasProperty("onlyRealServer")) {
        defaultConfig.testInstrumentationRunnerArguments["annotation"] =
            "com.viecz.vieczandroid.e2e.RealServerTest"
    }

    packaging {
        resources {
            excludes += listOf(
                "META-INF/LICENSE.md",
                "META-INF/LICENSE-notice.md"
            )
        }
    }
}

// Convenience tasks for split E2E test profiles
tasks.register<Exec>("connectedMockE2E") {
    description = "Run only mock-server E2E tests (no backend needed)"
    group = "verification"
    workingDir = project.rootDir
    commandLine(
        "${project.rootDir}/gradlew",
        "connectedDevDebugAndroidTest",
        "-PexcludeRealServer"
    )
}

tasks.register<Exec>("connectedRealServerE2E") {
    description = "Run only real-server E2E tests (requires Go test server on :9999)"
    group = "verification"
    workingDir = project.rootDir
    // Use localhost for physical devices (adb reverse), 10.0.2.2 for emulators
    val serverHost = project.findProperty("testServerHost")?.toString() ?: "localhost"
    commandLine(
        "${project.rootDir}/gradlew",
        "connectedDevDebugAndroidTest",
        "-PonlyRealServer",
        "-Pandroid.testInstrumentationRunnerArguments.testServerHost=$serverHost"
    )
}

// Workaround for Hilt Gradle plugin compatibility issue with AGP 8.12+
// See: https://github.com/google/dagger/issues/4976
hilt {
    enableAggregatingTask = false
}

// Enable JaCoCo coverage for Robolectric tests
// See: https://github.com/robolectric/robolectric/issues/5575
tasks.withType<Test> {
    configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.navigation.fragment.ktx)
    implementation(libs.androidx.navigation.ui.ktx)

    // Compose BOM
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    implementation(libs.compose.activity)
    implementation(libs.compose.navigation)

    // Debug dependencies
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)

    // Networking
    implementation(libs.retrofit)
    implementation(libs.retrofit.moshi)
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)

    // JSON
    implementation(libs.moshi)
    implementation(libs.moshi.kotlin)
    ksp(libs.moshi.codegen)

    // ViewModel & Lifecycle
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.lifecycle.runtime.compose)

    // DataStore for token storage
    implementation(libs.datastore.preferences)

    // Encrypted SharedPreferences for secure token storage
    implementation(libs.security.crypto)

    // Room Database
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    // Hilt Dependency Injection
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.hilt.navigation.compose)

    // Firebase
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.auth)

    // Phone number validation
    implementation(libs.libphonenumber)

    // Google Sign-In / Credential Manager
    implementation(libs.credentials)
    implementation(libs.credentials.play.services.auth)
    implementation(libs.googleid)
    implementation(libs.maplibre.android)

    // Image loading
    implementation(libs.coil.compose)

    // Benchmark profile installer
    implementation(libs.profileinstaller)

    // Design System Catalog (Showkase — dev flavor only)
    "devImplementation"(libs.showkase)
    "kspDev"(libs.showkase.processor)

    // Testing - Unit tests (JVM)
    testImplementation(libs.junit)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.mockk)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.turbine)
    testImplementation(libs.mockwebserver)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.junit)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    testImplementation(libs.compose.ui.test.manifest)

    // Testing - Instrumented tests (Android)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.espresso.intents)
    androidTestImplementation(libs.mockk.android)
    androidTestImplementation(libs.kotlin.test)
    androidTestImplementation(libs.coroutines.test)
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.compose.ui.test.junit4)
    androidTestImplementation(libs.hilt.android.testing)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.mockwebserver)
    kspAndroidTest(libs.hilt.compiler)
}

// Shared JaCoCo file filters for generated code
val jacocoFileFilter = listOf(
    "**/R.class", "**/R\$*.class", "**/BuildConfig.*",
    "**/Manifest*.*", "**/*Test*.*", "**/android/**/*.*",
    // Hilt generated
    "**/*_HiltModules*.*", "**/*_Factory.*", "**/*_MembersInjector.*",
    "**/Hilt_*.*", "**/*Module_*.*",
    // Dagger generated
    "**/Dagger*Component*.*", "**/*_Provide*Factory.*",
    // Moshi generated
    "**/*JsonAdapter.*"
)

tasks.register<JacocoReport>("jacocoTestReport") {
    dependsOn("testDevDebugUnitTest")

    reports {
        xml.required.set(true)
        html.required.set(true)
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/html"))
    }

    val debugTree = fileTree(layout.buildDirectory.dir("tmp/kotlin-classes/devDebug")) {
        exclude(jacocoFileFilter)
    }

    sourceDirectories.setFrom(files("src/main/java"))
    classDirectories.setFrom(debugTree)
    executionData.setFrom(fileTree(layout.buildDirectory) {
        include("outputs/unit_test_code_coverage/devDebugUnitTest/testDevDebugUnitTest.exec")
        include("jacoco/testDevDebugUnitTest.exec")
    })
}

// Package-specific JaCoCo report task
// Usage: ./gradlew jacocoPackageReport -PjacocoPackage=data/api
tasks.register<JacocoReport>("jacocoPackageReport") {
    dependsOn("testDevDebugUnitTest")

    val pkg = project.findProperty("jacocoPackage")?.toString() ?: "**"

    reports {
        xml.required.set(true)
        html.required.set(true)
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/package-html"))
    }

    val debugTree = fileTree(layout.buildDirectory.dir("tmp/kotlin-classes/devDebug")) {
        include("com/viecz/vieczandroid/$pkg/**")
        exclude(jacocoFileFilter)
    }

    sourceDirectories.setFrom(files("src/main/java"))
    classDirectories.setFrom(debugTree)
    executionData.setFrom(fileTree(layout.buildDirectory) {
        include("outputs/unit_test_code_coverage/devDebugUnitTest/testDevDebugUnitTest.exec")
        include("jacoco/testDevDebugUnitTest.exec")
    })
}
